<!-- header.inc -->
<header>
    <div class="logo-container">
        <img src="images/clouldspire_logo.png" alt="Cloudspire Logo" width="150">
        <h1 id="page_title">Cloudspire Technologies</h1>
    </div>
    <p class="tagline">Securing Tomorrow's Digital Landscape, Today.</p>
    <nav>
        <ul>
            <li><a href="jobs.php">Job Opportunities</a></li>
            <li><a href="about.php">About Us</a></li>
            <li><a href="apply.php">Apply now</a></li>
            <li><a href="mailto:info@cloudspire.com.au">Email Us</a></li>
        </ul>
    </nav>
    <hr>
</header>