<!-- header.inc -->
<header id="about_header">
    <img src="images/Screenshot_2025-04-08_214346.webp" id="logo" width="220" alt="CloudSpire Logo">
<hr>
    <h1 id="page_title">CloudSpire Technologies</h1>
    <nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="apply.php">Apply Now</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="manage.php">Queries</a></li>
            <li><a href="about.php">About Us</a></li>
        </ul>
    </nav>
</header>